config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :workshops, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :workshop
  after_create :update_workshop_sit_count


  private

  def update_workshop_sit_count
    workshop.update(remaining_site: workshop.total_sites - no_of_tickets)
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :bookings
    has_many :workshops, through: :bookings

    validates :full_name, :contact_number, presence: true
    validates :email, uniqueness: true, presence: true
end

app/models/workshop.rb
class Workshop < ApplicationRecord
    has_many :bookings
    has_many :customers, through: :bookings

    validates :name, :description, presence: true
    validates :start_date, :end_date, :start_time, :end_time , presence: true
    validates :total_sites, :registration_fee, presence: true
    validates :end_date, comparison: { greater_than: :start_date, message: 'can not be before start date' }

    def total_duration
        "From #{start_date} to #{end_date}"
    end

    def daily_workshop_duration
        "Everyday from #{start_time} to #{end_time}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
    def index
        @workshops = Workshop.all
    end

    def show
        @workshop = Workshop.find(params[:id])
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
        when :notice then 'alert alert-success'
        when :alert then 'alert alert-success'
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webinari</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/header"%>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Webinari</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Resources
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/workshops/index.html.erb
<div class="col-lg-12">
    <h3 class="mt-4 mb-4">Listing workshops</h3>
    <div class="row">
        <% @workshops.each do |workshop| %>
            <div class="col-lg-6">
                <div class="card shadow mb-3 mt-2">
                    <div class="card-body">
                        <h4 class="card-title"> <%= workshop.name %> </h4>
                        <p class="lead"><%= truncate(workshop.description, length: 50) %></p>
                        <h4><span class="badge bg-primary"> <%= workshop.total_duration %></span></h4>
                        <h4><span class="badge bg-primary"><%= workshop.daily_workshop_duration %></span></h4>
                        <%= link_to 'View Details', workshop, class: "btn btn-danger btn-lg"%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/workshops/show.html.erb
<div class="col-lg-8 mt-4">
    <div class="card shadow mb-3">
        <div class="card-body">
            <h4 class="card-title"><%= @workshop.name %></h4> 
            <div class="row mt-3">
                <div class="col-lg-7">
                    <h4><span class="badge bg-primary"><%= @workshop.total_duration%></span></h4>
                    <h4><span class="badge bg-primary"><%= @workshop.daily_workshop_duration %></span></h4>
                </div>
                <div class="col-lg-5">
                    <h4> Total Sits: <span class="badge bg-primary"><%= @workshop.total_sites %></span></h4>
                    <h4> Remaining Sits: <span class="badge bg-primary" ><%= @workshop.remaining_site %></span></h4> 
                    <h4> Registration Fee: <span class="badge bg-primary"><%= @workshop.registration_fee %></span></h4>
                </div>
            </div>
            <p class="lead mt-3 mb-3"><%= @workshop.description %> </p>
            <%= link_to 'Back to Workshops', workshops_path, class: "btn btn-outline-danger btn-lg mt-3" %>
        </div>
    </div>
</div>
<div class="col-lg-4 mt-4">
    <div class="card shadow mb-3">
        <div class="card-body">
            <h4 class="card-title mb-2">Reserve your sit now!</h4>
            <%= form_with url: "#", data: { turbo: false } do |form | %>
                <%= form.hidden_field :workshop_id, value: @workshop.id %>
                <div class="form-group">
                    <%= form.label :full_name, class: "mb-2 mt-2" %> 
                    <%= form.text_field :full_name, class: "form-control", required: true %>
                </div>
                <div class="form-group">
                    <%= form.label :email, class: "mb-2 mt-2" %>
                    <%= form.text_field :email, class: "form-control", required: true %>
                </div>
                <div class="form-group">
                    <%= form.label :contact_number, class: "mb-2 mt-2" %>
                    <%= form.text_field :contact_number, class: "form-control", required: true %>
                </div>
                <div class="form-group">
                    <%= form.label :no_of_seats_you_want_to_book, class: "mb-2 mt-2" %>
                    <%= form.number_field :no_of_tickets, class: "form-control", required: true, min: 1, max: @workshop.remaining_site %>
                </div>
                <h4 class="mt-4 mb-3"> Card Details </h4>
                <div class="form-group">
                    <%= form.label :card_number, class: "mb-2 mt-2" %>
                    <%= form.text_field :card_number, class: "form-control", required: true %>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <%= form.label :cvv, class: "mb-2 mt-2" %>
                            <%= form.text_field :cvv, class: "form-control", required: true, maxlength: 4 %>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <%= form.label :month, class: "mb-2 mt-2" %>
                            <%= form.number_field :exp_month, class: "form-control", required: true, min: 1, max: 12 %>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="form-group">
                            <%= form.label :year, class: "mb-2 mt-2" %>
                            <%= form.number_field :exp_year, class: "form-control", required: true, min: 2022, max: 2026 %>
                        </div>
                    </div>
                </div>
                <div class="d-grid gap-2">
                    <%= form.submit "Book Your Ticket Now", class: "btn btn-outline-danger btn-lg mt-3"%>
                </div>
            <% end %>
        </div>
    </div>
</div>